//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeINC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataAcEntities1 : DbContext
    {
        public DataAcEntities1()
            : base("name=DataAcEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Больничные> Больничные { get; set; }
        public virtual DbSet<Должности> Должности { get; set; }
        public virtual DbSet<Отделы> Отделы { get; set; }
        public virtual DbSet<Отпуски> Отпуски { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
    }
}
