//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeINC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Больничные
    {
        public int ID_Больничные { get; set; }
        public Nullable<int> ID_Сотрудника { get; set; }
        public Nullable<System.DateTime> Дата_начала { get; set; }
        public Nullable<System.DateTime> Дата_завершения { get; set; }
        public Nullable<int> Номер_больничного { get; set; }
        public string Диагноз { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
