//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeINC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отпуски
    {
        public int ID_Отпуска { get; set; }
        public Nullable<System.DateTime> Дата_начала { get; set; }
        public Nullable<System.DateTime> Дата_завершения { get; set; }
        public Nullable<int> ID_Cотрудника { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
